version: 0.2

phases:
  install:
    commands:
      - echo "Installing prerequisites..."
      - apt-get update && apt-get install -y zip  # Ensure 'zip' is installed
  pre_build:
    commands:
      - echo "Extracting changed directories from webhook payload..."
      - export PAYLOAD=$(cat webhook_payload.json)
      - echo "$PAYLOAD" | jq -r '.commits[].modified[], .commits[].added[]' | awk -F'/' '{print $1}' | sort -u > changed_dirs.txt
      - export CHANGED_DIRS=$(cat changed_dirs.txt)
  build:
    commands:
      - echo "Build Stage start"
      - echo "Build Stage end"
  post_build:
    commands:
      - echo "Post Build start"
      - echo "Post Build end"

