version: 0.2

phases:
  install:
    commands:
      - echo "Installing prerequisites..."
      - apt-get update && apt-get install -y zip  # Ensure 'zip' is installed
  pre_build:
    commands:
      - echo "Reading GitHub payload from CodePipeline artifact..."
      - ls -al $CODEBUILD_SRC_DIR
      - cat $CODEBUILD_SRC_DIR/buildspec.yaml
      - cat $CODEBUILD_SRC_DIR/versions.json
  build:
    commands:
      - echo "Build Stage start"
      - echo "Build Stage end"
  post_build:
    commands:
      - echo "Post Build start"
      - echo "Post Build end"

