version: 0.2

env:
  variables:
    CHANGED_DIR: ""

phases:
  pre_build:
    commands:
      - echo "Detecting changed directories..."
      - export CHANGED_DIR=$(git diff --name-only HEAD HEAD~1 | grep '/$' | head -n 1 | cut -d '/' -f 1)
      - echo "Changed directory: $CHANGED_DIR"
  install:
    commands:
      - pip install -r $CHANGED_DIR/requirements.txt
  build:
    commands:
      - zip -r function.zip $CHANGED_DIR
  post_build:
    commands:
      - aws s3 cp function.zip s3://${LAMBDA_BUCKET_NAME}/lambda/
      - version=$(date +%Y%m%d%H%M%S)
      - aws s3 cp function.zip s3://${LAMBDA_BUCKET_NAME}/lambda/function-${version}.zip