name: Track Changes in lift-club-lambda
on:
  push:
    branches:
      - main
    paths:
      - 'lift-club-lambda/**' # Run only if changes are in lift-club-lambda directory

jobs:
  log-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log Changes for lift-club-lambda
        run: |
          # Handle cases where there might not be a previous commit
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            echo "Changes detected in lift-club-lambda:" >> lift-club-lambda/log.txt
            git diff --name-only HEAD^ HEAD -- lift-club-lambda/ >> lift-club-lambda/log.txt
          else
            echo "No previous commit. Assuming initial changes in lift-club-lambda:" >> lift-club-lambda/log.txt
            git diff --name-only HEAD -- lift-club-lambda/ >> lift-club-lambda/log.txt
          fi
          git add lift-club-lambda/log.txt
          git commit -m "Log changes in lift-club-lambda"
          git push