name: Track Changes in lift-club-lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lift-club-lambda/**' # Run only if changes are in lift-club-lambda directory

jobs:
  log-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log Changes for lift-club-lambda
        run: |
          echo "Changes detected in lokos-blog-crud/..."
          echo "Updating versions.json..."
          if [ ! -f versions.json ]; then
            echo "{}" > versions.json
          fi
          cp versions.json versions_old.json
          while IFS= read -r dir; do
            if jq -e ".\"$dir\"" versions.json > /dev/null; then
              jq ".\"$dir\" += 1" versions.json > tmp.json && mv tmp.json versions.json
            else
              jq ".\"$dir\" = 1" versions.json > tmp.json && mv tmp.json versions.json
            fi
          done < changed_dirs.txt
          echo "Updated versions.json:"
          cat versions.json 